# Generated by Django 2.1.4 on 2019-01-05 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('responsible_name', models.CharField(max_length=30, null=True)),
                ('telephone', models.CharField(max_length=14, null=True)),
                ('birthday', models.DateField(null=True)),
                ('school', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(choices=[('1f', '1º ano - fundamental'), ('2f', '2º ano - fundamental'), ('3f', '3º ano - fundamental'), ('4f', '4º ano - fundamental'), ('5f', '5º ano - fundamental'), ('6f', '6º ano - fundamental'), ('7f', '7º ano - fundamental'), ('8f', '8º ano - fundamental'), ('9a', '9º ano - fundamental'), ('1em', '1º ano - médio'), ('2em', '1º ano - médio'), ('3em', '1º ano - médio'), ('others', 'Outro')], max_length=20, null=True)),
                ('adress', models.TextField(max_length=400)),
                ('subject', models.CharField(choices=[('mat', 'Matemática'), ('port', 'Português'), ('ingles', 'Inglês'), ('ciencia', 'Ciências'), ('geo', 'Geografia'), ('hist', 'História'), ('outra', 'Outra disciplina')], max_length=20, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
