# Generated by Django 2.1.4 on 2019-01-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('1f', '1º ano - fundamental'), ('2f', '2º ano - fundamental'), ('3f', '3º ano - fundamental'), ('4f', '4º ano - fundamental'), ('5f', '5º ano - fundamental'), ('6f', '6º ano - fundamental'), ('7f', '7º ano - fundamental'), ('8f', '8º ano - fundamental'), ('9a', '9º ano - fundamental'), ('1em', '1º ano - médio'), ('2em', '2º ano - médio'), ('3em', '3º ano - médio'), ('others', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='responsible_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject',
            field=models.CharField(choices=[('mat', 'Matemática'), ('port', 'Português'), ('ingles', 'Inglês'), ('ciencia', 'Ciências'), ('geo', 'Geografia'), ('hist', 'História'), ('outra', 'Outra disciplina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='telephone',
            field=models.CharField(max_length=14),
        ),
    ]
