# Generated by Django 2.1.4 on 2019-01-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('1f', '1º ano - fundamental'), ('2f', '2º ano - fundamental'), ('3f', '3º ano - fundamental'), ('4f', '4º ano - fundamental'), ('5f', '5º ano - fundamental'), ('6f', '6º ano - fundamental'), ('7f', '7º ano - fundamental'), ('8f', '8º ano - fundamental'), ('9a', '9º ano - fundamental'), ('1em', '1º ano - médio'), ('2em', '2º ano - médio'), ('3em', '3º ano - médio'), ('others', 'Outro')], max_length=20, null=True),
        ),
    ]
