# Generated by Django 2.1.4 on 2019-01-09 00:30

from django.db import migrations
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dom', 'Domingo'), ('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado')], max_length=30),
            preserve_default=False,
        ),
    ]
